name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Update README with latest Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@anitaa_1990"
        env:
          # Use PAT from Secrets
          GITHUB_TOKEN: ${{ secrets.PAT_1 }}

      - name: Push changes
        run: |
          git config user.name "anitaa1990"
          git config user.email "anitaa1990@users.noreply.github.com"
          git remote set-url origin https://anitaa1990:${{ secrets.PAT_1 }}@github.com/anitaa1990/anitaa1990.git
          git add README.md
          git commit -m "Update blog posts"
          git push
